# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

# File copied and modified from https://github.com/andreasdahl1987/DahlDesignProperties/blob/master/.github/workflows/dotnet.yaml
# Credits and thanks to them!

name: Create SimHub plugin DLL

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: What Properties version does this correspond to?
        required: true
      is-pre-release:
        type: boolean
        required: true
        description: "is this a prerelease version?"

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Setup MS Build Systems
      uses: microsoft/setup-msbuild@v1.1

    - uses: actions/cache@v3
      name: Restore Caches
      id: cache
      with:
        path: |
          innounp050.rar
          SimHub.8.01.2.zip
        key: SimHub.8.01.2

    - name: Download Requirements # Used to download the SimHub DLLs - only if not in cache.
      if: steps.cache.outputs.cache-hit != 'true'
      run: | 
        aria2c -j1 -o innounp050.rar "https://sourceforge.net/projects/innounp/files/innounp/innounp%200.50/innounp050.rar/download"
        aria2c -j1 -o SimHub.8.01.2.zip "https://github.com/SHWotever/SimHub/releases/download/8.1.2/SimHub.8.01.2.zip"
    
    - name: Extract Requirements # Used to extract the SimHub DLLs
      run: | 
        7z x innounp050.rar
        7z x SimHub.8.01.2.zip
        dir
        mkdir "C:\Program Files (x86)\SimHub\"
        D:\a\DiyFfbPedalTestRepo\DiyFfbPedalTestRepo\innounp.exe -v -x -b -e -d"C:\Program Files (x86)\SimHub\" SimHubSetup_8.1.2.exe GameReaderCommon.dll SimHub.plugins.dll

    - name: List files in dir
      run: |
        ls "C:\Program Files (x86)\SimHub\"
        
    - name: List files in dir 2
      run: |
        ls ${{ github.workspace }}
          
    - name: Restore Packages
      run: nuget restore "SimHubPlugin/User.PluginSdkDemo.sln"

    - name: Build solution
      run: msbuild "SimHubPlugin/User.PluginSdkDemo.sln" -t:rebuild -property:Configuration=Release

    - name: Upload Artifact
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'D:\a\DahlDesignProperties\SimHubPlugin\bin\DiyActivePedal.dll'
        prerelease: ${{ github.event.inputs.is-pre-release }}
        replacesArtifacts: true
        allowUpdates: true
        name: ${{ github.event.inputs.version }}
        tag: ${{ github.event.inputs.version }}
